
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;


/**
 * ClassMakerFrame.java created by levenick on Jan 14, 2013 at 11:35:23 AM
 */
public class ClassMakerFrame extends javax.swing.JFrame {

    public ClassMakerFrame() {  // this constructor creates the form and displays it
        initComponents();
        setTitle("classmaker");
        setSize(800,550);
        setVisible(true);
    }

    /** You can't modify the following code; it is regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        outTA = new javax.swing.JTextArea();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        inTA.setColumns(20);
        inTA.setRows(5);
        inTA.setText("class Foo {\n    int x;\n    String name;\n}");
        jScrollPane1.setViewportView(inTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 300, 330);

        outTA.setColumns(20);
        outTA.setRows(5);
        jScrollPane2.setViewportView(outTA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 20, 380, 500);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(convertButton);
        convertButton.setBounds(80, 390, 93, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        ClassMaker cm = new ClassMaker();
		outTA.setText(cm.makeIt(inTA.getText()));
                outTA.selectAll();
                
                StringSelection stringSelection = new StringSelection( outTA.getSelectedText() );
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents( stringSelection, null );
    }//GEN-LAST:event_convertButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JTextArea inTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outTA;
    // End of variables declaration//GEN-END:variables

}